### ISSUE TITLE
lpips-jax repository seems to be disappeared from the huggingface community.

### ISSUE THREAD

**Issue by jmyoon1** [pcuenca/lpips-j#2]
I was using `lpips-j` repository for training our model with LPIPS loss.
Since about 5 hrs ago, the following message occurs:
```
Repository Not Found for url: https://huggingface.co/pcuenq/lpips-jax/resolve/main/lpips_lin.h5.
Please make sure you specified the correct `repo_id` and `repo_type`.
```
and we found that `lpips-jax` repository disappeared from the huggingface community.
Is there any issues on the code or repository?

**Comment by orcinus** [comment]
Just noticed the same.
Went to start another training run using LPIPS as one of the losses and got a nasty surprise.

**Comment by jmyoon1** [comment]
If you already downloaded the `lpips_lin.h5`and `vgg16_weights.h5` files by prior training runs, consider replacing the following line (about line 51) at `lpips.py` file,
```
        # weights_file = hf_hub_download(repo_id="pcuenq/lpips-jax", filename="lpips_lin.h5")
        weights_file = '/home/<username>/.cache/huggingface/hub/models--pcuenq--lpips-jax/snapshots/1a6ac7498dac36b0f588fe33cd1c5a4ba55d5d4f/lpips_lin.h5'
```

and the vgg network (about line 28).
```
        weights_file = '/home/<username>/.cache/huggingface/hub/models--pcuenq--lpips-jax/snapshots/1a6ac7498dac36b0f588fe33cd1c5a4ba55d5d4f/vgg16_weights.h5'
        # weights_file = hf_hub_download(repo_id="pcuenq/lpips-jax", filename="vgg16_weights.h5")
```
I found the directory where the `lpips_lin.h5` and `vgg16_weights.h5` locates by the command
`find / -name <filename>`.

**Comment by pcuenca** [comment]
Hi @jmyoon1, @orcinus! It will be back, there's a temporary issue with some repos that is being resolved: https://twitter.com/huggingface/status/1655760648926642178?s=61&t=1yWn7LxWEU1-vRBf24_Orw

Sorry for the trouble!

**Comment by pcuenca** [comment]
@jmyoon1 thanks for the suggestion to use the cache!

**Comment by orcinus** [comment]
@pcuenca No worries, realized immediately after that Huggingface was having CDN issues (at least appears like it). And also fished the weights out of cache just before i crashed to bed.

**Comment by pcuenca** [comment]
The repo has been restored now. Closing this issue :)
